
[general]

	[general.emotes]
		rank_emotes = true

	[general.party_commands]
		party_commands = true
		party_command_feedback = true

[settings]

	[settings."§eoverall"]
		overall = true

	[settings."§emessage_3"]
		third_message_to_notify_on_discord = ""
		change_third_message_to_search_for_words = false

	[settings."§emessage_2"]
		second_message_to_notify_on_discord = ""
		change_second_message_to_search_for_words = false

	[settings."§esettings"]
		chat_feedback = true

	[settings."§emessage_5"]
		change_fourth_message_to_search_for_words = false
		fifth_message_to_notify_on_discord = ""

	[settings."§emessage_4"]
		change_fourth_message_to_search_for_words = false
		fourth_message_to_notify_on_discord = ""

	[settings."§emessage_1"]
		change_first_message_to_search_for_words = false
		first_message_to_notify_on_discord = ""

[debug]

	[debug.area]
		"\"soon\"_debug_area_on_join" = false
		debug_area_on_join = true

	[debug.inventory]
		debug_sponge_test = false

[discord]

	[discord."§ewebhook"]
		discord_user_avatar = ""
		webhook_url = ""
		color_for_the_discord_embed = "255,0,255,0"
		bot_username = ""

	[discord."§esettings"]
		include_timestamp = true
		discord_user_ping = ""
		custom_message = ""
		include_ingame_message = true
		ping_everyone = false
		include_used_account = true

[hud]

	[hud.hud]
		hud_color = "255,255,19,240"
		ping_display = false
		search_bar = true
		tps_display = false
		fps_display = false

[dungeons]

	[dungeons.general]
		auto_requeue_mode = 0

[crimson_isle]

	[crimson_isle.miniboss]
		crimson_miniboos_esp = true
		crimson_isle_miniboos_esp = true

	[crimson_isle.dojo]
		auto_discipline = true

[mining]

	[mining.crystal_nukleus]
		auto_crystal_material = false

	[mining.crystal_hollows]
		yog_esp = true
		automaton_sludge = true
		"fast_/enterthecrystalhollows" = true
		automaton_esp = true
		team_treasurite_esp = true
		sludge_esp = true
		goblin_esp = true

	[mining.crystal_nucleus_runs]
		jungle_temple_cheese = true
		goblin_egg_amount = 1
		auto_crystal_material_amethyst = true
		auto_crystal_material_amber = true
		auto_crystal_material_sapphire = true

[dungeon]

	[dungeon.watcher]
		chat_announce_watcher = true
		title_announce_watcher = true

	[dungeon.general]
		auto_requeue_delay = 0
		"\"soon\"_insta_ghost_stonk" = false
		auto_requeue_mode = 0
		auto_requeue = true
		highlight_color = "255,255,30,30"
		auto_leap_clear = 0
		death_hater = true
		title_announce_key = true
		exclude_own_death = true
		death_message_text = "{name} died. lol"
		insta_ghost_stonk = true
		highlight_in_leap_menu = 1
		title_announce_door_open = true
		auto_leap_boss = 0

	[dungeon.livid]
		"\"soon\"_anti_blindness" = false
		anti_blindness = true

	[dungeon.blood_rush]
		title_announce_key = true
		chat_announce_watcher = true
		key_esp = true
		title_announce_watcher = true
		pearl_door = true
		title_announce_door_open = true

	[dungeon.terminals]
		announce_melody = true
		announce_melody_progress = true
		announce_melody_text = "doing the HELL NAH terminal"

[misc]

	[misc.search]
		"\"soon\"_auto_item_to_inventory" = false
		nbt_data = true
		search_bar = true
		search_bar_accuracy = true
		auto_item_to_inventory = true

	[misc.anvil]
		auto_anvil_book_combine = true

	[misc.inventory]
		inventory_search = true
		"\"soon\"_auto_item_to_inventory" = false
		auto_item_to_inventory = false

	[misc.bazaar]
		empty_sack_bazaar_search = true

